networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge

services:
  tts-service:       

      build:
        context: .
        dockerfile: Dockerfile
        args:
          SERVICE_NAME: sentiric-tts-service

      env_file: 
        - ./.env.docker

      # volumes:
      #   - ../sentiric-infrastructure/tls/certs:/etc/sentiric/tls:ro

      ports:
        - "${TTS_SERVICE_PORT}:${TTS_SERVICE_PORT}"

      networks:
        - sentiric-net
      
      profiles:
        - default
        - ai

      restart: always

      # mem_limit: 2048m # <-- Bu satırı geçici olarak yorum satırı yapın veya
      mem_limit: 6g # <-- 6GB gibi daha yüksek bir değere ayarlayın
      cpus: '2.0'