networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge

services:
  tts-service:       

      build:
        context: .
        dockerfile: Dockerfile
        args:
          SERVICE_NAME: sentiric-tts-service

      env_file: 
        - ./.env

      # volumes:
      #   - ../sentiric-infrastructure/tls/certs:/etc/sentiric/tls:ro

      ports:
        - "${TTS_SERVICE_PORT}:${TTS_SERVICE_PORT}"

      networks:
        - sentiric-net
      
      profiles:
        - default
        - ai

      restart: always

      mem_limit: 512m
      cpus: 0.5      