[project]
name = "sentiric-tts-service"
version = "0.1.0"
description = "Text-to-Speech service for Sentiric Platform."
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "structlog",
    "python-dotenv",
    # Renkli konsol logları için GEREKLİ
    "colorama>=0.4.6"
]